import {TAU,catmullRom,clamp,lerp,mulberry32,randRange,sampleCurve,v3Length,v3Normalize,v3Sub} from './math.js';
export const COLORS=Object.freeze({hanji:[.96,.90,.76],ivory:[.98,.96,.89],gold:[.93,.61,.13],softGold:[1,.78,.35],blue:[.08,.42,.82],cyan:[.08,.72,.86],red:[.77,.12,.18],green:[.06,.48,.31],white:[.92,.98,1],navy:[.02,.09,.17],violet:[.43,.18,.68],ink:[.018,.045,.075]});
const OBANG=[COLORS.white,COLORS.gold,COLORS.blue,COLORS.red,COLORS.green];
const tempDir=[0,0,0];
const cloneColor=c=>[c[0],c[1],c[2]];
const midpoint=(a,b)=>[(a[0]+b[0])*.5,(a[1]+b[1])*.5,(a[2]+b[2])*.5];
function segmentFromPoints(a,b,color=COLORS.ivory,group=0,delay=0,emission=.6,seed=.5){v3Sub(tempDir,b,a);const length=v3Length(tempDir)||.001;return{position:midpoint(a,b),direction:v3Normalize([0,0,0],tempDir),length,color:cloneColor(color),group,delay,emission,seed};}
function addLine(out,a,b,sub,color,meta={}){const count=Math.max(1,sub|0);for(let i=0;i<count;i++){const t0=i/count,t1=(i+1)/count,p0=[lerp(a[0],b[0],t0),lerp(a[1],b[1],t0),lerp(a[2],b[2],t0)],p1=[lerp(a[0],b[0],t1),lerp(a[1],b[1],t1),lerp(a[2],b[2],t1)];out.push(segmentFromPoints(p0,p1,color,meta.group||0,meta.delay??t0,meta.emission??.65,meta.seed??((i+.5)/count)));}}
function addCurve(out,controls,sub,color,meta={}){const points=sampleCurve(controls,sub+1);for(let i=0;i<sub;i++)out.push(segmentFromPoints(points[i],points[i+1],color,meta.group||0,meta.delay??(i/sub),meta.emission??.7,meta.seed??((i+.5)/sub)));}
function addEllipse(out,center,rx,ry,rotation,sub,color,depthWave=0,meta={}){const points=[],c=Math.cos(rotation),s=Math.sin(rotation);for(let i=0;i<=sub;i++){const angle=TAU*i/sub,x=Math.cos(angle)*rx,y=Math.sin(angle)*ry;points.push([center[0]+x*c-y*s,center[1]+x*s+y*c,center[2]+Math.sin(angle*2)*depthWave]);}for(let i=0;i<sub;i++)out.push(segmentFromPoints(points[i],points[i+1],color,meta.group||0,meta.delay??(i/sub),meta.emission??.7,meta.seed??((i+.5)/sub)));}
function generateLatticeSegments(density=1){
 const out=[],z=0,w=7.6,h=4.8,frame=Math.round(28*density),iv=COLORS.ivory,gold=COLORS.softGold;
 addLine(out,[-w/2,-h/2,z],[w/2,-h/2,z],frame,gold,{emission:.95});addLine(out,[w/2,-h/2,z],[w/2,h/2,z],Math.round(18*density),gold,{emission:.95});addLine(out,[w/2,h/2,z],[-w/2,h/2,z],frame,gold,{emission:.95});addLine(out,[-w/2,h/2,z],[-w/2,-h/2,z],Math.round(18*density),gold,{emission:.95});
 const inner=.18;addLine(out,[-w/2+inner,-h/2+inner,z+.04],[w/2-inner,-h/2+inner,z+.04],frame,iv);addLine(out,[w/2-inner,-h/2+inner,z+.04],[w/2-inner,h/2-inner,z+.04],Math.round(18*density),iv);addLine(out,[w/2-inner,h/2-inner,z+.04],[-w/2+inner,h/2-inner,z+.04],frame,iv);addLine(out,[-w/2+inner,h/2-inner,z+.04],[-w/2+inner,-h/2+inner,z+.04],Math.round(18*density),iv);
 for(let i=-2;i<=2;i++){const x=i*1.25;addLine(out,[x,-2.15,z+.02],[x,2.15,z+.02],Math.round(20*density),iv,{delay:(i+2)/5});}
 for(let i=-1;i<=1;i++){const y=i*1.15;addLine(out,[-3.5,y,z-.01],[3.5,y,z-.01],Math.round(30*density),iv,{delay:(i+1)/3});}
 const xs=[-2.5,0,2.5],ys=[-1.15,1.15];for(let row=0;row<ys.length;row++)for(let col=0;col<xs.length;col++){const cx=xs[col],cy=ys[row],phase=(row*xs.length+col)/6;for(let petal=0;petal<8;petal++){const angle=petal/8*TAU+Math.PI/8,rad=[Math.cos(angle),Math.sin(angle)],tan=[-rad[1],rad[0]],center=[cx,cy,z+.08*Math.sin(angle*2)],controls=[center,[cx+rad[0]*.35+tan[0]*.30,cy+rad[1]*.35+tan[1]*.30,z+.10],[cx+rad[0]*.78+tan[0]*.06,cy+rad[1]*.78+tan[1]*.06,z+.02],[cx+rad[0]*.35-tan[0]*.30,cy+rad[1]*.35-tan[1]*.30,z-.06],center];addCurve(out,controls,Math.round(7*density),petal%2?iv:gold,{delay:clamp(phase*.55+petal/16),emission:petal%2?.66:.9});}addEllipse(out,[cx,cy,z+.12],.22,.22,0,Math.round(14*density),gold,.03,{emission:.92,delay:phase});}
 const step=.58;for(let x=-3.2;x<=3.2;x+=step){addLine(out,[x-.7,-2.15,z-.08],[x+.7,-1.1,z-.08],Math.round(5*density),iv,{emission:.45});addLine(out,[x+.7,1.1,z-.08],[x-.7,2.15,z-.08],Math.round(5*density),iv,{emission:.45});}
 return out;
}
function threadControlPoints(index){const y=(index-2)*.58,depth=(index-2)*.18,wave=index%2===0?1:-1;return[[-3.65,y*.45,.1+depth],[-2.4,y+wave*.25,-.4+depth],[-1,y*.35-wave*.55,-1.2+depth],[.4,y*.72+wave*.35,-1.7+depth],[1.9,y*.25-wave*.42,-1.25+depth],[3.5,y*.55+wave*.18,-.4+depth]];}
function generateThreadSegments(count,rng){const out=[],per=Math.ceil(count/5);for(let strand=0;strand<5;strand++){const points=sampleCurve(threadControlPoints(strand),per+1);for(let i=0;i<per;i++)out.push(segmentFromPoints(points[i],points[i+1],OBANG[strand],0,clamp(i/per*.82+strand*.035),.86,rng()));}return out.slice(0,count);}
function pointAlongThread(index,t,offset=0){const points=threadControlPoints(index),position=catmullRom(points,clamp(t),[0,0,0]),ahead=catmullRom(points,clamp(t+.005),[0,0,0]),direction=v3Normalize([0,0,0],v3Sub([0,0,0],ahead,position));position[1]+=offset;return{position,direction,color:OBANG[index]};}
function generateMagpiePoints(count,rng){
 const points=new Array(count);
 for(let i=0;i<count;i++){
  const choice=rng();let position,direction,color,wing=0,regionDelay=0;
  if(choice<.30){
   const u=randRange(rng,-1,1),angle=rng()*TAU,r=Math.sqrt(Math.max(0,1-u*u));
   position=[-.05+u*1.08,.02+Math.cos(angle)*r*.55,Math.sin(angle)*r*.34];direction=[1,Math.cos(angle)*.16,Math.sin(angle)*.10];
   const chest=position[1]<-.05&&position[0]>.12;color=chest?COLORS.white:(rng()<.27?COLORS.cyan:COLORS.navy);regionDelay=.14+(u+1)*.11;
  }else if(choice<.42){
   const angle=rng()*TAU,v=randRange(rng,-1,1),r=Math.sqrt(Math.max(0,1-v*v));
   position=[.94+v*.46,.27+Math.cos(angle)*r*.42,.02+Math.sin(angle)*r*.36];direction=[1,.12,.02];color=rng()<.25?COLORS.cyan:COLORS.navy;regionDelay=.36;
  }else if(choice<.67){
   const u=Math.pow(rng(),.80),v=randRange(rng,-1,1),fan=Math.sin(u*Math.PI*.96);
   position=[-.20-2.58*u+.46*u*u+v*.10,.38+1.98*fan*(.84+.16*(1-Math.abs(v)))+v*.18,.16+v*.42+.10*Math.sin(u*Math.PI)];
   direction=[-1,.62-u*.24,v*.16];color=u>.82&&rng()<.52?COLORS.white:(rng()<.20?COLORS.softGold:(rng()<.52?COLORS.cyan:COLORS.blue));wing=1;regionDelay=.21+u*.25;
  }else if(choice<.79){
   const u=Math.pow(rng(),.84),v=randRange(rng,-1,1),fan=Math.sin(u*Math.PI*.95);
   position=[-.14-2.18*u+.36*u*u+v*.09,.08-1.12*fan+v*.15,-.31+v*.31-.06*Math.sin(u*Math.PI)];
   direction=[-1,-.43+u*.15,v*.12];color=rng()<.20?COLORS.white:(rng()<.50?COLORS.cyan:COLORS.navy);wing=.64;regionDelay=.26+u*.21;
  }else if(choice<.94){
   const feather=rng()<.5?-1:1,u=rng();
   position=[-.88-3.62*u,-.15+feather*(.13+.25*u)+Math.sin(u*Math.PI)*.13,feather*(.18+.09*u)];direction=[-1,feather*.11,feather*.04];
   color=u>.76?COLORS.white:(rng()<.20?COLORS.blue:COLORS.navy);regionDelay=.05+u*.27;
  }else if(choice<.985){
   const u=rng(),spread=(1-u)*.15;position=[1.30+u*.78,.29+randRange(rng,-spread,spread),randRange(rng,-spread,spread)];direction=[1,0,0];color=COLORS.softGold;regionDelay=.52;
  }else{
   const angle=rng()*TAU,r=rng()*.085;position=[1.16,.46+Math.cos(angle)*r,.34+Math.sin(angle)*r];direction=[1,0,0];color=COLORS.gold;regionDelay=.58;
  }
  direction=v3Normalize(direction,direction);points[i]={position,direction,color:cloneColor(color),group:wing,delay:clamp(regionDelay+randRange(rng,-.05,.05)),emission:color===COLORS.navy?.45:.95,seed:rng()};
 }
 return points;
}
const knotControls=[[-5.3,-.05,0],[-3.7,.02,.1],[-2.5,.78,.32],[-1.35,1.55,.52],[-.10,.72,.12],[-1.05,-.18,-.30],[-1.75,-1.34,.24],[-.25,-1.73,.58],[1.08,-.72,.10],[.12,.22,-.33],[.92,1.38,.42],[2.18,1.15,.20],[3.30,.05,.08],[5.35,0,0]];
function pointAlongKnot(t,strand=0){const position=catmullRom(knotControls,clamp(t),[0,0,0]),ahead=catmullRom(knotControls,clamp(t+.0035),[0,0,0]),direction=v3Normalize([0,0,0],v3Sub([0,0,0],ahead,position)),offset=(strand-2)*.105,side=v3Normalize([0,0,0],[-direction[1],direction[0],.3*Math.sin(t*TAU*2+strand)]);position[0]+=side[0]*offset;position[1]+=side[1]*offset;position[2]+=side[2]*offset;return{position,direction,color:OBANG[strand]};}
function generateBridgePoints(count,rng){const points=new Array(count);for(let i=0;i<count;i++){const strand=i%5,t=clamp((Math.floor(i/5)+rng()*.35)/Math.ceil(count/5)),s=pointAlongKnot(t,strand);points[i]={position:s.position,direction:s.direction,color:cloneColor(s.color),group:0,delay:clamp(t*.70+strand*.035),emission:1,seed:rng()};}return points;}
function pointAlongLotus(index,count,rng){const branch=index%13,petalIndex=Math.floor(index/13)%8,layer=Math.floor(index/(13*8))%4,t=((Math.floor(index/(13*8*4))+rng()*.4)/Math.ceil(count/(13*8*4)))%1,angleBase=petalIndex/8*TAU+layer*.055;let radius,angle,z;if(branch<8){const u=clamp(t),petal=Math.pow(Math.sin(Math.PI*u),.78);radius=.42+petal*(2.25+layer*.19);angle=angleBase+(u-.5)*(.68-layer*.055)*(branch%2?1:-1);z=-.12+layer*.15+petal*.45;}else if(branch<11){radius=.72+layer*.50;angle=t*TAU+layer*.16;z=layer*.10;}else{radius=2.8+(branch-11)*.45;angle=t*TAU;z=-.22+.10*Math.sin(angle*8);}const position=[Math.cos(angle)*radius,Math.sin(angle)*radius,z],tangent=[-Math.sin(angle),Math.cos(angle),.18*Math.cos(angle*2)],color=branch<8?OBANG[(petalIndex+layer)%5]:(branch<11?COLORS.gold:COLORS.cyan);return{position,direction:v3Normalize(tangent,tangent),color:cloneColor(color),group:0,delay:clamp(petalIndex/8*.42+layer*.08+t*.3),emission:.96,seed:rng()};}
function generateLotusPoints(count,rng){const result=new Array(count);for(let i=0;i<count;i++)result[i]=pointAlongLotus(i,count,rng);return result;}
function generateBridgeSegments(count,rng){const out=new Array(count),per=Math.ceil(count/5);for(let i=0;i<count;i++){const strand=i%5,t0=Math.floor(i/5)/per,t1=Math.min(1,t0+1/per),a=pointAlongKnot(t0,strand),b=pointAlongKnot(t1,strand);out[i]=segmentFromPoints(a.position,b.position,a.color,0,clamp(t0*.75+strand*.03),1,rng());}return out;}
function generateLotusSegments(count,rng){const out=[],petals=8,layers=4,per=Math.max(8,Math.floor(count*.72/(petals*layers)));for(let layer=0;layer<layers;layer++)for(let petal=0;petal<petals;petal++){const angleBase=petal/petals*TAU+layer*.055,points=[];for(let i=0;i<=per;i++){const t=i/per,shape=Math.pow(Math.sin(Math.PI*t),.78),radius=.42+shape*(2.2+layer*.18),angle=angleBase+(t-.5)*(.66-layer*.05)*(petal%2?1:-1);points.push([Math.cos(angle)*radius,Math.sin(angle)*radius,-.1+layer*.15+shape*.42]);}const color=OBANG[(petal+layer)%5];for(let i=0;i<points.length-1;i++)out.push(segmentFromPoints(points[i],points[i+1],color,0,clamp(petal/8*.45+layer*.08+i/per*.28),1,rng()));}const rings=Math.max(3,Math.floor(count*.28/64));for(let ring=0;ring<rings;ring++)addEllipse(out,[0,0,-.18+ring*.1],.65+ring*.5,.65+ring*.5,ring*.08,64,ring%2?COLORS.gold:COLORS.cyan,.05,{emission:.9,delay:ring/rings});while(out.length<count){const petal=out.length%petals,angle=petal/petals*TAU,a=[Math.cos(angle)*.25,Math.sin(angle)*.25,.15],b=[Math.cos(angle)*.65,Math.sin(angle)*.65,.2];out.push(segmentFromPoints(a,b,COLORS.softGold,0,petal/petals,1,rng()));}return out.slice(0,count);}
function createInstanceData(fromItems,toItems,rng,options={}){const count=options.count||Math.max(fromItems.length,toItems.length),from=new Float32Array(count*3),to=new Float32Array(count*3),dirFrom=new Float32Array(count*3),dirTo=new Float32Array(count*3),scalePhase=new Float32Array(count*4),colorFrom=new Float32Array(count*3),colorTo=new Float32Array(count*3),extra=new Float32Array(count*4),thMin=options.thicknessMin??.025,thMax=options.thicknessMax??.055,lenScale=options.lengthScale??.5,fixed=options.fixedLength??null;for(let i=0;i<count;i++){const fi=fromItems[Math.floor(i/count*fromItems.length)%fromItems.length],ti=toItems[Math.floor(i/count*toItems.length)%toItems.length],th=randRange(rng,thMin,thMax),length=fixed??Math.max(.035,lerp(fi.length||.16,ti.length||.16,.5)*lenScale),phase=rng(),o3=i*3,o4=i*4;from.set(fi.position,o3);to.set(ti.position,o3);dirFrom.set(fi.direction||[0,0,1],o3);dirTo.set(ti.direction||[0,0,1],o3);scalePhase.set([th,th*randRange(rng,.72,1.18),length,phase],o4);colorFrom.set(fi.color||COLORS.ivory,o3);colorTo.set(ti.color||COLORS.gold,o3);extra.set([ti.group??fi.group??0,clamp(ti.delay??fi.delay??phase),Math.max(fi.emission??.5,ti.emission??.5),ti.seed??fi.seed??rng()],o4);}return{count,from,to,dirFrom,dirTo,scalePhase,colorFrom,colorTo,extra};}
function buildThreadPointTargets(count,rng){const targets=new Array(count);for(let i=0;i<count;i++){const strand=i%5,t=(Math.floor(i/5)+rng()*.45)/Math.ceil(count/5),s=pointAlongThread(strand,t,randRange(rng,-.08,.08));targets[i]={position:[s.position[0]+randRange(rng,-.08,.08),s.position[1]+randRange(rng,-.08,.08),s.position[2]+randRange(rng,-.12,.12)],direction:s.direction,color:cloneColor(s.color),seed:rng()};}return targets;}
function buildStarTargets(count,rng){const targets=new Array(count);for(let i=0;i<count;i++){const radius=randRange(rng,6,18),angle=rng()*TAU,y=randRange(rng,-6.5,6.5),depth=randRange(rng,-9,5);targets[i]={position:[Math.cos(angle)*radius*.72,y,depth+Math.sin(angle)*radius*.15],direction:[0,0,1],color:rng()<.18?COLORS.gold:(rng()<.45?COLORS.cyan:COLORS.white),seed:rng()};}return targets;}
function createParticleData(count,rng){const stars=buildStarTargets(count,rng),threads=buildThreadPointTargets(count,rng),magpie=generateMagpiePoints(count,rng),bridge=generateBridgePoints(count,rng),lotus=generateLotusPoints(count,rng),seed=new Float32Array(count*4),star=new Float32Array(count*3),thread=new Float32Array(count*3),mp=new Float32Array(count*3),bp=new Float32Array(count*3),lp=new Float32Array(count*3),color=new Float32Array(count*3);for(let i=0;i<count;i++){const o3=i*3,o4=i*4;seed.set([rng(),rng(),rng(),rng()],o4);star.set(stars[i].position,o3);thread.set(threads[i].position,o3);mp.set(magpie[i].position,o3);bp.set(bridge[i].position,o3);lp.set(lotus[i].position,o3);color.set(OBANG[i%5],o3);}return{count,seed,star,thread,magpie:mp,bridge:bp,lotus:lp,color};}
export function createProceduralAssets({density=1,particleCount=9000,seed=20260824}={}){const rng=mulberry32(seed),lattice=generateLatticeSegments(density),threads=generateThreadSegments(lattice.length,rng),latticeToThreads=createInstanceData(lattice,threads,rng,{count:lattice.length,thicknessMin:.021,thicknessMax:.046,lengthScale:.48}),featherCount=Math.round(2200*density),threadPoints=buildThreadPointTargets(featherCount,rng),magpiePoints=generateMagpiePoints(featherCount,rng),threadToMagpie=createInstanceData(threadPoints,magpiePoints,rng,{count:featherCount,thicknessMin:.030,thicknessMax:.075,fixedLength:.16}),bridgePoints=generateBridgePoints(featherCount,rng),crossed=magpiePoints.map(item=>({...item,position:[item.position[0]+1.6,item.position[1],item.position[2]]})),magpieToBridge=createInstanceData(crossed,bridgePoints,rng,{count:featherCount,thicknessMin:.026,thicknessMax:.067,fixedLength:.14}),bridgeCount=Math.round(1120*density),bridgeSeg=generateBridgeSegments(bridgeCount,rng),lotusSeg=generateLotusSegments(bridgeCount,rng),bridgeToLotus=createInstanceData(bridgeSeg,lotusSeg,rng,{count:bridgeCount,thicknessMin:.020,thicknessMax:.043,lengthScale:.50}),particles=createParticleData(particleCount,rng);return{latticeToThreads,threadToMagpie,magpieToBridge,bridgeToLotus,particles,stats:{latticeSegments:latticeToThreads.count,featherInstances:threadToMagpie.count,bridgeSegments:bridgeToLotus.count,particles:particleCount}};}
